export { default } from "./src/wallet-manager-cosmos.js";
export { default as WalletAccountCosmos } from "./src/wallet-account-cosmos.js";
export type FeeRates = import("@tetherto/wdk-wallet").FeeRates;
export type KeyPair = import("@tetherto/wdk-wallet").KeyPair;
export type TransactionResult = import("@tetherto/wdk-wallet").TransactionResult;
export type TransferOptions = import("@tetherto/wdk-wallet").TransferOptions;
export type TransferResult = import("@tetherto/wdk-wallet").TransferResult;
export type CosmosWalletConfig = import("./src/wallet-account-cosmos.js").CosmosWalletConfig;
export type ResolvedChainConfig = import("./src/chain-config-resolver.js").ResolvedChainConfig;
export type DirectSignDocJson = import("./src/wallet-account-cosmos.js").DirectSignDocJson;
export type SignDirectParams = import("./src/wallet-account-cosmos.js").SignDirectParams;
export type SignDirectResult = import("./src/wallet-account-cosmos.js").SignDirectResult;
export type SignAminoParams = import("./src/wallet-account-cosmos.js").SignAminoParams;
export type SignAminoResult = import("./src/wallet-account-cosmos.js").SignAminoResult;
export { default as SeedSignerCosmos, ISignerCosmos } from "./src/signers/seed-signer-cosmos.js";
export { resolveChainConfig, getAvailableChains, isKnownChain } from "./src/chain-config-resolver.js";
